//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/CacheModificationResponse.msg.
//

#ifndef __INET_CACHEMODIFICATIONRESPONSE_M_H
#define __INET_CACHEMODIFICATIONRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class CacheModificationResponse;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>messages/CacheModificationResponse.msg:7</tt> by opp_msgtool.
 * <pre>
 * class CacheModificationResponse extends FieldsChunk
 * {
 *     int objectToDelete;	// id of object we are deleting
 * }
 * </pre>
 */
class CacheModificationResponse : public ::inet::FieldsChunk
{
  protected:
    int objectToDelete = 0;

  private:
    void copy(const CacheModificationResponse& other);

  protected:
    bool operator==(const CacheModificationResponse&) = delete;

  public:
    CacheModificationResponse();
    CacheModificationResponse(const CacheModificationResponse& other);
    virtual ~CacheModificationResponse();
    CacheModificationResponse& operator=(const CacheModificationResponse& other);
    virtual CacheModificationResponse *dup() const override {return new CacheModificationResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getObjectToDelete() const;
    virtual void setObjectToDelete(int objectToDelete);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CacheModificationResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CacheModificationResponse& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::CacheModificationResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CacheModificationResponse*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CACHEMODIFICATIONRESPONSE_M_H

