//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/ClientRequest.msg.
//

#ifndef __INET_CLIENTREQUEST_M_H
#define __INET_CLIENTREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class ClientRequest;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>messages/ClientRequest.msg:7</tt> by opp_msgtool.
 * <pre>
 * class ClientRequest extends FieldsChunk
 * {
 *     int objectId;
 * }
 * </pre>
 */
class ClientRequest : public ::inet::FieldsChunk
{
  protected:
    int objectId = 0;

  private:
    void copy(const ClientRequest& other);

  protected:
    bool operator==(const ClientRequest&) = delete;

  public:
    ClientRequest();
    ClientRequest(const ClientRequest& other);
    virtual ~ClientRequest();
    ClientRequest& operator=(const ClientRequest& other);
    virtual ClientRequest *dup() const override {return new ClientRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getObjectId() const;
    virtual void setObjectId(int objectId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClientRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClientRequest& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ClientRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ClientRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CLIENTREQUEST_M_H

