//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/DNSResponse.msg.
//

#ifndef __INET_DNSRESPONSE_M_H
#define __INET_DNSRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class DNSResponse;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>messages/DNSResponse.msg:7</tt> by opp_msgtool.
 * <pre>
 * class DNSResponse extends FieldsChunk
 * {
 *     int serverId;	// if -1 then it is origin server because no surrogate has object in cache
 *     int objectId;
 * }
 * </pre>
 */
class DNSResponse : public ::inet::FieldsChunk
{
  protected:
    int serverId = 0;
    int objectId = 0;

  private:
    void copy(const DNSResponse& other);

  protected:
    bool operator==(const DNSResponse&) = delete;

  public:
    DNSResponse();
    DNSResponse(const DNSResponse& other);
    virtual ~DNSResponse();
    DNSResponse& operator=(const DNSResponse& other);
    virtual DNSResponse *dup() const override {return new DNSResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getServerId() const;
    virtual void setServerId(int serverId);

    virtual int getObjectId() const;
    virtual void setObjectId(int objectId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DNSResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DNSResponse& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DNSResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DNSResponse*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DNSRESPONSE_M_H

