//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/DNSRequest.msg.
//

#ifndef __INET_DNSREQUEST_M_H
#define __INET_DNSREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class DNSRequest;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>messages/DNSRequest.msg:7</tt> by opp_msgtool.
 * <pre>
 * class DNSRequest extends FieldsChunk
 * {
 *     int objectId;	// id of the object the surrogate needs
 *     int connId;	// the id of the connecttion of client and surrogate server which wants the object
 *     int surrogateId;
 * }
 * </pre>
 */
class DNSRequest : public ::inet::FieldsChunk
{
  protected:
    int objectId = 0;
    int connId = 0;
    int surrogateId = 0;

  private:
    void copy(const DNSRequest& other);

  protected:
    bool operator==(const DNSRequest&) = delete;

  public:
    DNSRequest();
    DNSRequest(const DNSRequest& other);
    virtual ~DNSRequest();
    DNSRequest& operator=(const DNSRequest& other);
    virtual DNSRequest *dup() const override {return new DNSRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getObjectId() const;
    virtual void setObjectId(int objectId);

    virtual int getConnId() const;
    virtual void setConnId(int connId);

    virtual int getSurrogateId() const;
    virtual void setSurrogateId(int surrogateId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DNSRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DNSRequest& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DNSRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DNSRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DNSREQUEST_M_H

