//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/FinishMsg.msg.
//

#ifndef __FINISHMSG_M_H
#define __FINISHMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class FinishMsg;
/**
 * Class generated from <tt>messages/FinishMsg.msg:1</tt> by opp_msgtool.
 * <pre>
 * message FinishMsg
 * {
 * }
 * </pre>
 */
class FinishMsg : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const FinishMsg& other);

  protected:
    bool operator==(const FinishMsg&) = delete;

  public:
    FinishMsg(const char *name=nullptr, short kind=0);
    FinishMsg(const FinishMsg& other);
    virtual ~FinishMsg();
    FinishMsg& operator=(const FinishMsg& other);
    virtual FinishMsg *dup() const override {return new FinishMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FinishMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FinishMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline FinishMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<FinishMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FINISHMSG_M_H

