//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/LoadDataMsg.msg.
//

#ifndef __INET_LOADDATAMSG_M_H
#define __INET_LOADDATAMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class LoadDataMsg;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>messages/LoadDataMsg.msg:7</tt> by opp_msgtool.
 * <pre>
 * class LoadDataMsg extends FieldsChunk
 * {
 *     int load;
 *     int surrogateId;
 * }
 * </pre>
 */
class LoadDataMsg : public ::inet::FieldsChunk
{
  protected:
    int load = 0;
    int surrogateId = 0;

  private:
    void copy(const LoadDataMsg& other);

  protected:
    bool operator==(const LoadDataMsg&) = delete;

  public:
    LoadDataMsg();
    LoadDataMsg(const LoadDataMsg& other);
    virtual ~LoadDataMsg();
    LoadDataMsg& operator=(const LoadDataMsg& other);
    virtual LoadDataMsg *dup() const override {return new LoadDataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getLoad() const;
    virtual void setLoad(int load);

    virtual int getSurrogateId() const;
    virtual void setSurrogateId(int surrogateId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LoadDataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LoadDataMsg& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::LoadDataMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::LoadDataMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_LOADDATAMSG_M_H

