//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/ObjectMsg.msg.
//

#ifndef __OBJECTMSG_M_H
#define __OBJECTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ObjectMsg;
/**
 * Class generated from <tt>messages/ObjectMsg.msg:1</tt> by opp_msgtool.
 * <pre>
 * message ObjectMsg
 * {
 *     int objectId;
 *     int size;
 * }
 * </pre>
 */
class ObjectMsg : public ::omnetpp::cMessage
{
  protected:
    int objectId = 0;
    int size = 0;

  private:
    void copy(const ObjectMsg& other);

  protected:
    bool operator==(const ObjectMsg&) = delete;

  public:
    ObjectMsg(const char *name=nullptr, short kind=0);
    ObjectMsg(const ObjectMsg& other);
    virtual ~ObjectMsg();
    ObjectMsg& operator=(const ObjectMsg& other);
    virtual ObjectMsg *dup() const override {return new ObjectMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getObjectId() const;
    virtual void setObjectId(int objectId);

    virtual int getSize() const;
    virtual void setSize(int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ObjectMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ObjectMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ObjectMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ObjectMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OBJECTMSG_M_H

