//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/ObjectRequest.msg.
//

#ifndef __INET_OBJECTREQUEST_M_H
#define __INET_OBJECTREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class ObjectRequest;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>messages/ObjectRequest.msg:7</tt> by opp_msgtool.
 * <pre>
 * class ObjectRequest extends FieldsChunk
 * {
 *     int objectId;	// id of the object the surrogate needs
 * }
 * </pre>
 */
class ObjectRequest : public ::inet::FieldsChunk
{
  protected:
    int objectId = 0;

  private:
    void copy(const ObjectRequest& other);

  protected:
    bool operator==(const ObjectRequest&) = delete;

  public:
    ObjectRequest();
    ObjectRequest(const ObjectRequest& other);
    virtual ~ObjectRequest();
    ObjectRequest& operator=(const ObjectRequest& other);
    virtual ObjectRequest *dup() const override {return new ObjectRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getObjectId() const;
    virtual void setObjectId(int objectId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ObjectRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ObjectRequest& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ObjectRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ObjectRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_OBJECTREQUEST_M_H

