//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/RetryMsg.msg.
//

#ifndef __RETRYMSG_M_H
#define __RETRYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class RetryMsg;
/**
 * Class generated from <tt>messages/RetryMsg.msg:1</tt> by opp_msgtool.
 * <pre>
 * message RetryMsg
 * {
 *     int connId;
 * }
 * </pre>
 */
class RetryMsg : public ::omnetpp::cMessage
{
  protected:
    int connId = 0;

  private:
    void copy(const RetryMsg& other);

  protected:
    bool operator==(const RetryMsg&) = delete;

  public:
    RetryMsg(const char *name=nullptr, short kind=0);
    RetryMsg(const RetryMsg& other);
    virtual ~RetryMsg();
    RetryMsg& operator=(const RetryMsg& other);
    virtual RetryMsg *dup() const override {return new RetryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getConnId() const;
    virtual void setConnId(int connId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RetryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RetryMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline RetryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<RetryMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RETRYMSG_M_H

